/*
  Practica 2 - Jenkinsfile dummy (PUNTO DE PARTIDA)

  Este Jenkinsfile es intencionalmente simple. En la Practica 2 iras anadiendo
  piezas (stages, agents, funciones Groovy, Docker build, docker compose, etc.)
  hasta construir un pipeline CI/CD completo.
*/

def runInDocker(String image, Closure body) {
  docker.image(image).inside { body() }
}

pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }

    stage('CI - Build tools image') {
      steps {
        script {
          env.CI_IMAGE_NAME = "java-ci-tools:${env.BUILD_NUMBER}"
          docker.build(env.CI_IMAGE_NAME, "-f devops/ci.Dockerfile .")
        }
      }
    }

    stage('CI - Lint') {
      steps {
        script{
          runInDocker(env.CI_IMAGE_NAME) { sh 'make lint' }
        }
      }
    }

    stage('CI - Test') {
      steps {
         script{
          runInDocker(env.CI_IMAGE_NAME) { sh 'make test' }
         }
      }
    }

     stage('CI - Build image') {
      steps {
        script {
          env.IMAGE_REPO_LOCAL = 'scalian_training-java-hello-world'
          env.IMAGE_VERSION = '0.0.2'
          env.IMAGE_LOCAL = "${env.IMAGE_REPO_LOCAL}:${env.IMAGE_VERSION}"
          docker.build(env.IMAGE_LOCAL, "--build-arg VERSION=${env.IMAGE_VERSION} -f devops/Dockerfile .")
        }
      }
    }

    stage('CD') {
      //when {
      //  allOf {
      //    anyOf {
      //      branch 'develop'
      //      branch 'master'
      //    }
          // TODO (E6.3): Solo ejecutar CD si RUN_CD es true
      //  }
      //}
      steps {
        script {
          // TODO (E6.2): Define DEPLOY_ENV (develop=DEV, master=PRO) y muestra logs.
          // TODO (E6): docker compose up -> logs -> docker compose down --volumes
          // Recomendado: encapsular con composeUpTestDown(...) (E9).
          sh 'docker compose up -d'
          sh 'sleep 5'
          sh 'curl http://localhost:8084/hello'
          sh 'docker compose down --volumes'
        }
      }
      //post {
        // =========================
        // Ejercicio 6.5 (hooks post)
        // =========================
      //  always {
          // TODO (E6.5): Limpieza garantizada
      //  }
      //  success {
          // TODO (E6.5): SUCCESS
      //  }
      //  failure {
          // TODO (E6.5): FAILURE + logs
       // }
      //}
    }

  }
}