/*
  Practica 2 - Jenkinsfile dummy (PUNTO DE PARTIDA)

  Este Jenkinsfile es intencionalmente simple. En la Practica 2 iras anadiendo
  piezas (stages, agents, funciones Groovy, Docker build, docker compose, etc.)
  hasta construir un pipeline CI/CD completo.
*/

pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }

    stage('CI - Build tools image') {
      steps {
        script {
          env.CI_IMAGE_NAME = "java-ci-tools:${env.BUILD_NUMBER}"
          docker.build(env.CI_IMAGE_NAME, "-f devops/ci.Dockerfile .")
        }
      }
    }

    stage('CI - Lint') {
      steps {
        script{
          docker.image(env.CI_IMAGE_NAME).inside { "make lint" }
        }
      }
    }

    stage('CI - Test') {
      steps {
         script{
          docker.image(env.CI_IMAGE_NAME).inside { "make test" }
         }
      }
    }
  }
}